"""
Django settings for health_predict project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import os

import paypalrestsdk

# from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1+6b6bmpzdsxf_8y6n_em#w_h)^nu0kf3d%95n8_d$$d)9=k@k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
BASE_URL = 'http://localhost:8000'

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'blog',
    'chat',
    'core',
    'dashboard',
    'doctor',
    'patient',
    'pharmacy',
    'ai_chat',
    'communication',
    'tinymce',
    'appiontment',
    'payment',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'health_predict2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'health_predict2.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('localhost', 6379)],  # Update to 'localhost' if Redis is local
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'uploads'
STATICFILES_DIRS = [
    BASE_DIR / "static",

]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.CustomUser'
MODEL_PATH = 'save_model/disease_prediction_model.h5'
LABEL_ENCODER_PATH = 'save_model/label_encoder.pkl'

# GENERATIVE_AI_KEY = config('GENERATIVE_AI_KEY')

TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'width': 720,
    'menubar': 'file edit view insert format tools table help',
    'plugins': 'advlist autolink lists link image charmap print preview hr anchor pagebreak',
    'toolbar': 'undo redo | bold italic underline | alignleft aligncenter alignright | bullist numlist outdent indent',
    'content_css': '/static/css/my_custom_styles.css',
}
STRIPE_PUBLIC_KEY = 'pk_test_51PyZ5pRrRKHQE8lSo9C8jdxLNPqNPhobAOB012HmHrEuBTgmdzYJKMtV2A5a3OWew2CC3cLP7y9PsxNPG0r56BbN00ySbICWr2'
STRIPE_SECRET_KEY = 'sk_test_51PyZ5pRrRKHQE8lS9m2q9S9oW2TvSRPV1tm2T9y3pszQHdbUvSMawzemATRFF2s1OZZQ6NzB4wVs8az9tBroFH3y00baa43eNT'
STRIPE_API_VERSION = '2024-04-10'
# STRIPE_WEBHOOK_SECRET = 'your_stripe_webhook_secret'

PAYPAL_CLIENT_ID = 'Ab6IHzd7SSL4awEfkc06r9aLMwWJ7Dwd1z3Jvr8E7msFj1OCG_-SpHiL6Uy-CMdEvSNJol6qiw_Mlc-1'
PAYPAL_CLIENT_SECRET = 'EGjpJA9mYBG3NiEGWksBfmuYpdbVDpdgf_1LgGe3nUY4uwy7t33eJQGjMct25AElaDjhdh_i5CafhRri'
PAYPAL_API_URL = 'https://api-m.sandbox.paypal.com'
PAYPAL_MODE = 'sandbox'  # Change to 'live' for production

paypalrestsdk.configure({
    "mode": PAYPAL_MODE,
    "client_id": PAYPAL_CLIENT_ID,
    "client_secret": PAYPAL_CLIENT_SECRET,
})

PAYPAL_RECEIVER_EMAIL = 'djangogirlssl@gmail.com'
PAYPAL_TEST = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'djangogirlssl@gmail.com'
EMAIL_HOST_PASSWORD = 'your-email-password'
