# Generated by Django 5.1 on 2024-09-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
